apiVersion: apps/v1
kind: Deployment
metadata:
  name: manju-micro
  labels:
    app: manju-micro
  namespace: manju
spec:
  replicas: 4
  selector:
    matchLabels:
      app: raman-micro
  template:
    metadata:
      labels:
        app: raman-micro
    spec:
      containers:
        - name: raman-micro
          image: ramann123/ssecure-raman-customer-orders-service:latest
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"

