apiVersion: v1
kind: Service
metadata:
  name: manju-micro
  namespace: manju
spec:
  selector:
    app: manju-micro
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort

